### ISSUE TITLE
Привет))

### ISSUE THREAD

**Issue by lov3catch** [bocharsky-bw/vkontakte-php-sdk#12]
Заброшено?

**Comment by bocharsky-bw** [comment]
Привет, зависит от того в чем вопрос. Я сейчас не использую VK API, поэтому активность тут маленькая. Но библиотекой вроде как по статистике пользуются, и PRs по прежнему приветсвуются :)

**Comment by lov3catch** [comment]
Это то, что я хотел услышать)
Планирую проект на вк-апи и ищу либу, многие мертвые.
Есть какие-то требования к ПРам? Стиль оформления и тд? Я раньше не контрибютил, но хочу попробывать))

**Comment by bocharsky-bw** [comment]
Особых требований нет, только стандартный набор: желательно выдерживать стиль кодирования, симфони и PSR код стандарты могут помочь: https://symfony.com/doc/current/contributing/code/standards.html . А также желательно использовать английский для того чтобы многие могли понять о чем идет речь в этой переписке или PR. Удачи :)
